// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VR360.Api.Infrastructure.Data;

#nullable disable

namespace VR360.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VR360.Api.Domain.Entities.Hotspot", b =>
                {
                    b.Property<Guid>("HotspotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NextSceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Pitch")
                        .HasColumnType("float");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Yaw")
                        .HasColumnType("float");

                    b.HasKey("HotspotId");

                    b.HasIndex("NextSceneId");

                    b.HasIndex("SceneId");

                    b.ToTable("Hotspots");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.HotspotTranslation", b =>
                {
                    b.Property<Guid>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HotspotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NoiDungPopup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDePopup")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UrlAudio")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TranslationId");

                    b.HasIndex("HotspotId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("HotspotTranslations");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.Scene", b =>
                {
                    b.Property<Guid>("SceneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaseUrlCDN")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("SlugDiTich")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SceneId");

                    b.HasIndex("SlugDiTich")
                        .IsUnique();

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.SceneTranslation", b =>
                {
                    b.Property<Guid>("TranslationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("SceneId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("UrlAudio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TranslationId");

                    b.HasIndex("SceneId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("SceneTranslations");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.Hotspot", b =>
                {
                    b.HasOne("VR360.Api.Domain.Entities.Scene", "NextScene")
                        .WithMany()
                        .HasForeignKey("NextSceneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("VR360.Api.Domain.Entities.Scene", "Scene")
                        .WithMany("Hotspots")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NextScene");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.HotspotTranslation", b =>
                {
                    b.HasOne("VR360.Api.Domain.Entities.Hotspot", "Hotspot")
                        .WithMany("Translations")
                        .HasForeignKey("HotspotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotspot");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.SceneTranslation", b =>
                {
                    b.HasOne("VR360.Api.Domain.Entities.Scene", "Scene")
                        .WithMany("Translations")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.Hotspot", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("VR360.Api.Domain.Entities.Scene", b =>
                {
                    b.Navigation("Hotspots");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
